# Generated by Django 3.1.4 on 2021-01-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='highlighted',
            new_name='highlight',
        ),
    ]
